name: Test
on:
  push:
  pull_request:
    types: [reopened]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -e ".[codestyle]"
      - name: Lint
        run: |
          isort --check-only .
          black --check .
          flake8 .
          pyupgrade --py37-plus **/*.py

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Django 2.2
          - django: "2.2"
            python: "3.7"
          - django: "2.2"
            python: "3.8"
          - django: "2.2"
            python: "3.9"
          # Django 3.0
          - django: "3.0"
            python: "3.7"
          - django: "3.0"
            python: "3.8"
          - django: "3.0"
            python: "3.9"
          # Django 3.1
          - django: "3.1"
            python: "3.7"
          - django: "3.1"
            python: "3.8"
          - django: "3.1"
            python: "3.9"
          # Django 3.2
          - django: "3.2"
            python: "3.7"
          - django: "3.2"
            python: "3.8"
          - django: "3.2"
            python: "3.9"
          - django: "3.2"
            python: "3.10"
          # Django 4.0
          - django: "4.0"
            python: "3.8"
          - django: "4.0"
            python: "3.9"
          - django: "4.0"
            python: "3.10"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install -e ".[testing]"
          pip install "django~=${{ matrix.django }}"
      - name: Test
        run: (cd demo; pytest)
      - uses: codecov/codecov-action@v2
        with:
          directory: ./demo/
